builds:
  - binary: giat
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: giat
    homepage: "https://github.com/hobbymarks/giat"
    tap:
      owner: hobbymarks
      name: homebrew-hobbymarks
    commit_author:
      name: hobbymarks
      email: ihobbymarks@gmail.com

checksum:
  name_template: 'checksums.txt'
