{% set ver = "2021.05.31" %}
{% set num = "1043" %}

package:
    name: giat
    version: {{ ver }}

build:
    number: {{ num }}
    skip: True # [py<38]
    entry_points:
        - giat = giat:run_main

source:
    git_url: https://github.com/hobbymarks/giat.git

requirements:
    build:
        - python
        - setuptools
    
    host:
        - python
        - setuptools
    
    run:
        - 'python>=3.8'
        - 'click>=8.0.0'
        - 'setuptools>=49.6.0'
        - 'unidecode>=1.2.0'
        - 'colorama>=0.4.4'
        - 'wcwidth>=0.2.5'

about:
    home: https://github.com/hobbymarks/giat.git
    description: To change local git dir to RepoName@OrganizationName format.
    license: MIT
    license_file: LICENSE
